--script general

--     @E:\THOR\BDOO_ENSIAS\BDOO_ENSIAS_2015\ROO_ENSIAS_2015\TP2_ROO_ADT_METHODES_2015\EXEMPLE_COURS\TP2_METHD_SCRIPT_GENE.sql
--- tracage
set echo on


set serveroutput on;

spool E:\THOR\BDOO_ENSIAS\BDOO_ENSIAS_2015\ROO_ENSIAS_2015\TP2_ROO_ADT_METHODES_2015\EXEMPLE_COURS\TP2_METHD_TRACES.txt


--nettopyage
drop table tab_pers;
drop type t_pers FORCE ;
drop table tab_adrs;
drop type t_adr FORCE ;

--1. creation du type T_ADR
@E:\THOR\BDOO_ENSIAS\BDOO_ENSIAS_2015\ROO_ENSIAS_2015\TP2_ROO_ADT_METHODES_2015\EXEMPLE_COURS\CREA_T_ADR.SQL
show error

--2. creation de la tables des adresses
@E:\THOR\BDOO_ENSIAS\BDOO_ENSIAS_2015\ROO_ENSIAS_2015\TP2_ROO_ADT_METHODES_2015\EXEMPLE_COURS\CREA_TAB_ADRS.SQL
show error

--3. creation de la tables des adresses
@E:\THOR\BDOO_ENSIAS\BDOO_ENSIAS_2015\ROO_ENSIAS_2015\TP2_ROO_ADT_METHODES_2015\EXEMPLE_COURS\CREA_T_PERS.SQL
show error

--4. creation de la table des personnes
@E:\THOR\BDOO_ENSIAS\BDOO_ENSIAS_2015\ROO_ENSIAS_2015\TP2_ROO_ADT_METHODES_2015\EXEMPLE_COURS\CREA_TAB_PERS.SQL
show error

--5. codage des méthodes de T_ADR
@E:\THOR\BDOO_ENSIAS\BDOO_ENSIAS_2015\ROO_ENSIAS_2015\TP2_ROO_ADT_METHODES_2015\EXEMPLE_COURS\CREA_METH_T_ADR.SQL
show error



-- FIN DE TRACAGE
SPOOL OFF;

