--script general

--     @E:\THOR\BDOO_EM\TP_ROO_EM_2015\TP4_ROO_NESTED_TABLE_2015\NESTED_SCRIPT_GENE.sql
--- tracage
set echo on


set serveroutput on;

spool E:\THOR\BDOO_EM\TP_ROO_EM_2015\TP4_ROO_NESTED_TABLE_2015\NESTED_CREATION_TRACES.txt


--nettopyage
drop TABLE 		TAB_CLASSES;
drop TABLE 		TAB_ELEVES;
drop TYPE 		T_CLASSE FORCE ;
DROP TYPE		T_LISTE_COURS FORCE ;
DROP TYPE		T_LISTE_SEANCES FORCE ;
DROP TYPE 		T_LISTE_ELEVES FORCE ;
drop TYPE		T_ELEVE FORCE ;
drop TYPE		T_SEANCE FORCE ;
                                     

--1. creation du type T_ELEVE ET T_LISTE_ELEVES (TYPE TABLE IMBRIQUEE)
@E:\THOR\BDOO_EM\TP_ROO_EM_2015\TP4_ROO_NESTED_TABLE_2015\CREA_T_ELEVE.SQL
show error

--2. creation du type T_SEANCE ET T_LISTE_SEANCES (TYPE TABLE IMBRIQUEE)
@E:\THOR\BDOO_EM\TP_ROO_EM_2015\TP4_ROO_NESTED_TABLE_2015\CREA_T_SEANCE.SQL
show error

--3. creation du type T_CLASSE ET T_LISTE_COURS (TYPE VARRAY IMBRIQUE)
@E:\THOR\BDOO_EM\TP_ROO_EM_2015\TP4_ROO_NESTED_TABLE_2015\CREA_T_CLASSE.SQL
show error

--4. creation de la tables des ELEVES
@E:\THOR\BDOO_EM\TP_ROO_EM_2015\TP4_ROO_NESTED_TABLE_2015\CREA_TAB_ELEVES.SQL
show error

--4. creation de la tables des CLASSES
@E:\THOR\BDOO_EM\TP_ROO_EM_2015\TP4_ROO_NESTED_TABLE_2015\CREA_TAB_CLASSES.SQL
show error


-- FIN DE TRACAGE
SPOOL OFF;

